// @generated by shadcnui-foundry - DO NOT EDIT MANUALLY
// Run `foundry generate accordion` to regenerate
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";

@customElement("foundry-accordion")
export class FoundryAccordionElement extends LitElement {
  @property({ type: String }) type: "single" | "multiple" = "single";

  override render() {
    return html`<div data-slot="accordion" data-type="${this.type}"><slot></slot></div>`;
  }
}
