import type { GeneratedFile, PipelineResult } from "@shadcnui-foundry/ir";
import type { Emitter, TransformedComponent } from "@shadcnui-foundry/core";

export class AngularEmitter implements Emitter {
  readonly framework = "angular";

  async emit(transformed: TransformedComponent): Promise<PipelineResult<GeneratedFile[]>> {
    const componentName = transformed.componentId
      .split("-")
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join("");
    const selector = `foundry-${transformed.componentId}`;

    const content = `// @generated by shadcnui-foundry
import { Component } from "@angular/core";

@Component({
  selector: "${selector}",
  standalone: true,
  template: \`
    <!-- TODO: implement ${componentName} -->
    <ng-content />
  \`,
})
export class ${componentName}Component {
  // TODO: implement inputs
}
`;
    return {
      success: true,
      data: [{
        path: `${transformed.componentId}/${transformed.componentId}.component.ts`,
        content,
        componentId: transformed.componentId,
        framework: "angular",
        generated: true,
        irHash: "",
      }],
    };
  }
}
