import type { GeneratedFile, PipelineResult } from "@shadcnui-foundry/ir";
import type { Emitter, TransformedComponent } from "@shadcnui-foundry/core";

export class SvelteEmitter implements Emitter {
  readonly framework = "svelte";

  async emit(transformed: TransformedComponent): Promise<PipelineResult<GeneratedFile[]>> {
    const content = `<!-- @generated by shadcnui-foundry -->
<script lang="ts">
  // TODO: implement ${transformed.componentId}
  let { class: className = "", ...restProps } = $props();
</script>

<div class="{className}" {...restProps}>
  <slot />
</div>
`;
    return {
      success: true,
      data: [{
        path: `${transformed.componentId}/${transformed.componentId}.svelte`,
        content,
        componentId: transformed.componentId,
        framework: "svelte",
        generated: true,
        irHash: "",
      }],
    };
  }
}
