import type { Emitter, TransformedComponent } from "@shadcnui-foundry/core";
import type {
  ComponentIR,
  GeneratedFile,
  PipelineResult,
  Prop,
  Variant,
} from "@shadcnui-foundry/ir";

function toPascalCase(value: string): string {
  return value
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function mapBaseTag(role: string | undefined): string {
  switch (role) {
    case "button":
      return "button";
    case "textbox":
      return "input";
    default:
      return "div";
  }
}

function mapPropertyType(prop: Prop): string {
  if ((prop.type === "enum" || prop.type === "union") && prop.values && prop.values.length > 0) {
    return prop.values.map((value) => `"${value}"`).join(" | ");
  }

  switch (prop.type) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return "unknown[]";
    case "object":
      return "Record<string, unknown>";
    case "function":
      return "(...args: unknown[]) => unknown";
    default:
      return "unknown";
  }
}

function ensureVariantProps(props: Prop[], variants: Variant[]): Prop[] {
  const merged = new Map<string, Prop>();

  for (const prop of props) {
    merged.set(prop.name, prop);
  }

  for (const variant of variants) {
    if (merged.has(variant.name)) {
      continue;
    }

    merged.set(variant.name, {
      name: variant.name,
      type: "enum",
      values: variant.values,
      required: false,
      ...(variant.defaultValue !== undefined && { defaultValue: `"${variant.defaultValue}"` }),
      forwarded: false,
      description: `Variant: ${variant.name}`,
    });
  }

  return [...merged.values()].filter((prop) => prop.name !== "children");
}

function inferDefault(prop: Prop): string | undefined {
  if (prop.defaultValue !== undefined) {
    return prop.defaultValue;
  }

  if (prop.type === "boolean") {
    return "false";
  }

  return undefined;
}

export class LitEmitter implements Emitter {
  readonly framework = "lit";

  async emit(transformed: TransformedComponent): Promise<PipelineResult<GeneratedFile[]>> {
    const componentName = toPascalCase(transformed.componentId);
    const tagName = `foundry-${transformed.componentId}`;
    const ir = (transformed.spec as { ir?: ComponentIR }).ir;
    const props = ir ? ensureVariantProps(ir.props, ir.variants) : [];
    const ariaAttrs = ir
      ? [...new Set([...ir.a11y.requiredAttributes, ...ir.a11y.optionalAttributes])].filter(
          (attr) => attr.startsWith("aria-"),
        )
      : [];

    const allProps: Prop[] = [
      ...props,
      ...ariaAttrs
        .filter((attr) => !props.some((prop) => prop.name === attr))
        .map((attr) => ({
          name: attr,
          type: "string" as const,
          required: false,
          forwarded: false,
          description: `Accessibility attribute: ${attr}`,
        })),
    ];

    const propertyLines = allProps
      .sort((a, b) => a.name.localeCompare(b.name))
      .map((prop) => {
        const type = mapPropertyType(prop);
        const defaultValue = inferDefault(prop);
        const init = defaultValue !== undefined ? ` = ${defaultValue}` : "";
        return `  @property({ attribute: ${JSON.stringify(prop.name)} }) ${JSON.stringify(prop.name)}!: ${type}${init};`;
      });

    const variantAttrs = ir
      ? ir.variants
          .map((variant) => `      data-${variant.name}=\"\${this[\"${variant.name}\"] ?? ""}\"`)
          .join("\n")
      : "";

    const ariaBindings = allProps
      .filter((prop) => prop.name.startsWith("aria-"))
      .map((prop) => `      ${prop.name}=\"\${this[\"${prop.name}\"] ?? ""}\"`)
      .join("\n");

    const role = ir?.a11y.roles[0];
    const roleLine = role ? `      role=\"${role}\"\n` : "";
    const baseTag = mapBaseTag(role);

    const content = `// @generated by shadcnui-foundry — DO NOT EDIT MANUALLY
// Run \`foundry generate ${transformed.componentId}\` to regenerate
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";

@customElement("${tagName}")
export class ${componentName}Element extends LitElement {
${propertyLines.join("\n")}

  override render() {
    return html\`
      <${baseTag}
${roleLine}${variantAttrs}
${ariaBindings}
      >
        <slot></slot>
      </${baseTag}>
    \`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "${tagName}": ${componentName}Element;
  }
}
`;
    return {
      success: true,
      data: [
        {
          path: `${transformed.componentId}/${tagName}.ts`,
          content,
          componentId: transformed.componentId,
          framework: "lit",
          generated: true,
          irHash: "",
        },
      ],
    };
  }
}
