// @generated by shadcnui-foundry - DO NOT EDIT MANUALLY
// Run `foundry generate card` to regenerate
import { LitElement, html } from "lit";
import { customElement } from "lit/decorators.js";

@customElement("foundry-card")
export class FoundryCardElement extends LitElement {
  override render() {
    return html`<div data-slot="card"><slot></slot></div>`;
  }
}
