import type { Emitter, TransformedComponent } from "@shadcnui-foundry/core";
import type { GeneratedFile, PipelineResult } from "@shadcnui-foundry/ir";

/**
 * Emits React TSX source files from a transformed component spec.
 *
 * Generated files include a provenance header comment.
 *
 * @generated false
 */
export class ReactEmitter implements Emitter {
  readonly framework = "react";

  async emit(transformed: TransformedComponent): Promise<PipelineResult<GeneratedFile[]>> {
    const { componentName, propsInterface, a11y } = transformed.spec as {
      componentName: string;
      propsInterface: Array<{
        name: string;
        type: string;
        required: boolean;
        defaultValue?: string;
        description?: string;
      }>;
      a11y: { roles: string[] };
    };

    const propsLines = propsInterface.map((p) => {
      const opt = p.required ? "" : "?";
      const comment = p.description ? `  /** ${p.description} */\n` : "";
      return `${comment}  ${p.name}${opt}: ${p.type};`;
    });

    const defaultsLines = propsInterface
      .filter((p) => p.defaultValue !== undefined)
      .map((p) => `  ${p.name} = ${p.defaultValue},`);

    const ariaRole = a11y.roles[0] ?? undefined;
    const roleAttr = ariaRole ? `\n      role="${ariaRole}"` : "";

    const content = `// ============================================================
// @generated by shadcnui-foundry — DO NOT EDIT MANUALLY
// Source: shadcn/ui registry
// Run \`foundry generate ${transformed.componentId}\` to regenerate
// ============================================================
import * as React from "react";
import { cn } from "../utils/cn.js";

export interface ${componentName}Props extends React.HTMLAttributes<HTMLElement> {
${propsLines.join("\n")}
}

const ${componentName} = React.forwardRef<HTMLElement, ${componentName}Props>(
  function ${componentName}(
    {
${defaultsLines.join("\n")}
      className,
      ...props
    },
    ref
  ) {
    return (
      <div
        ref={ref}${roleAttr}
        className={cn("${transformed.componentId}", className)}
        {...props}
      />
    );
  }
);
${componentName}.displayName = "${componentName}";

export { ${componentName} };
`;

    const file: GeneratedFile = {
      path: `${transformed.componentId}/${componentName}.tsx`,
      content,
      componentId: transformed.componentId,
      framework: "react",
      generated: true,
      irHash: "",
    };

    return { success: true, data: [file] };
  }
}
