import type { Emitter, TransformedComponent } from "@shadcnui-foundry/core";
import type { GeneratedFile, PipelineResult } from "@shadcnui-foundry/ir";

type ReactPropSpec = {
  name: string;
  type: string;
  required: boolean;
  defaultValue?: string;
  description?: string;
};

type ReactVariantSpec = {
  name: string;
  values: string[];
  defaultValue?: string;
};

type ReactA11ySpec = {
  roles: string[];
  requiredAttributes: string[];
  optionalAttributes: string[];
};

type ReactSpec = {
  componentName: string;
  propsInterface: ReactPropSpec[];
  variants: ReactVariantSpec[];
  a11y: ReactA11ySpec;
};

function mapBaseElement(role: string | undefined): {
  htmlTag: string;
  domElement: string;
  attrType: string;
} {
  switch (role) {
    case "button":
      return {
        htmlTag: "button",
        domElement: "HTMLButtonElement",
        attrType: "ButtonHTMLAttributes",
      };
    case "textbox":
      return { htmlTag: "input", domElement: "HTMLInputElement", attrType: "InputHTMLAttributes" };
    default:
      return { htmlTag: "div", domElement: "HTMLDivElement", attrType: "HTMLAttributes" };
  }
}

function escapeJsString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/\"/g, '\\"');
}

function ensureVariantProps(props: ReactPropSpec[], variants: ReactVariantSpec[]): ReactPropSpec[] {
  const merged = new Map<string, ReactPropSpec>();

  for (const prop of props) {
    merged.set(prop.name, prop);
  }

  for (const variant of variants) {
    if (merged.has(variant.name)) {
      continue;
    }

    merged.set(variant.name, {
      name: variant.name,
      type: variant.values.map((value) => `"${value}"`).join(" | ") || "string",
      required: false,
      ...(variant.defaultValue !== undefined && {
        defaultValue: `"${escapeJsString(variant.defaultValue)}"`,
      }),
      description: `Variant: ${variant.name}`,
    });
  }

  return [...merged.values()].sort((a, b) => a.name.localeCompare(b.name));
}

function createA11yPropSpecs(a11y: ReactA11ySpec): ReactPropSpec[] {
  const attrs = [...new Set([...a11y.requiredAttributes, ...a11y.optionalAttributes])];

  return attrs
    .filter((attr) => attr.startsWith("aria-"))
    .map((attr) => ({
      name: attr,
      type: "string",
      required: a11y.requiredAttributes.includes(attr),
      description: `Accessibility attribute: ${attr}`,
    }));
}

export class ReactEmitter implements Emitter {
  readonly framework = "react";

  async emit(transformed: TransformedComponent): Promise<PipelineResult<GeneratedFile[]>> {
    const { componentName, propsInterface, variants, a11y } = transformed.spec as ReactSpec;
    const allProps = ensureVariantProps(propsInterface, variants);
    const a11yProps = createA11yPropSpecs(a11y);
    const allPropsWithA11y = [...allProps, ...a11yProps].filter((prop) => prop.name !== "children");

    const primaryRole = a11y.roles[0];
    const roleAttr = primaryRole ? ` role="${primaryRole}"` : "";
    const baseElement = mapBaseElement(primaryRole);

    const propsLines = allPropsWithA11y.map((p) => {
      const opt = p.required ? "" : "?";
      const comment = p.description ? `  /** ${p.description} */\n` : "";
      return `${comment}  ${p.name}${opt}: ${p.type};`;
    });

    const defaultsLines = allPropsWithA11y
      .filter((p) => p.defaultValue !== undefined)
      .map((p) => `  ${p.name} = ${p.defaultValue},`);

    const variantNames = variants.map((variant) => variant.name);
    const variantDataAttrs = variantNames
      .map((name) => `        data-${name}={${name} !== undefined ? ${name} : undefined}`)
      .join("\n");

    const attributePropType = `React.${baseElement.attrType}<${baseElement.domElement}>`;

    const classNameBase = escapeJsString(transformed.componentId);

    const content = `// @generated by shadcnui-foundry — DO NOT EDIT MANUALLY
// Run \`foundry generate ${transformed.componentId}\` to regenerate
import * as React from "react";
import { cn } from "../utils/cn.js";

export interface ${componentName}Props extends ${attributePropType} {
${propsLines.join("\n")}
}

const ${componentName} = React.forwardRef<${baseElement.domElement}, ${componentName}Props>(
  function ${componentName}(
    {
${defaultsLines.join("\n")}
      className,
      ...props
    },
    ref
  ) {
    return (
      <${baseElement.htmlTag}
        ref={ref}${roleAttr}
${variantDataAttrs}
        className={cn("${classNameBase}", className)}
        {...props}
      />
    );
  }
);
${componentName}.displayName = "${componentName}";

export { ${componentName} };
`;

    const file: GeneratedFile = {
      path: `${transformed.componentId}/${componentName}.tsx`,
      content,
      componentId: transformed.componentId,
      framework: "react",
      generated: true,
      irHash: "",
    };

    return { success: true, data: [file] };
  }
}
