import type { Emitter, TransformedComponent } from "@shadcnui-foundry/core";
import type { GeneratedFile, PipelineResult } from "@shadcnui-foundry/ir";

export class VueEmitter implements Emitter {
  readonly framework = "vue";

  async emit(transformed: TransformedComponent): Promise<PipelineResult<GeneratedFile[]>> {
    const { componentName } = transformed.spec as { componentName: string };
    const content = `<!-- @generated by shadcnui-foundry -->
<script setup lang="ts">
// TODO: implement ${componentName}
defineOptions({ name: "${componentName}" });
</script>

<template>
  <div class="${transformed.componentId}">
    <slot />
  </div>
</template>
`;
    return {
      success: true,
      data: [
        {
          path: `${transformed.componentId}/${componentName}.vue`,
          content,
          componentId: transformed.componentId,
          framework: "vue",
          generated: true,
          irHash: "",
        },
      ],
    };
  }
}
