// @generated by shadcnui-foundry - DO NOT EDIT MANUALLY
// Run `foundry generate button` to regenerate
import { LitElement, html } from "lit";
import { customElement } from "lit/decorators.js";

@customElement("foundry-button")
export class FoundryButtonElement extends LitElement {
  override render() {
    return html`<button data-slot="button"><slot></slot></button>`;
  }
}
