// @generated by shadcnui-foundry - DO NOT EDIT MANUALLY
// Run `foundry generate input` to regenerate
import { LitElement, html } from "lit";
import { customElement } from "lit/decorators.js";

@customElement("foundry-input")
export class FoundryInputElement extends LitElement {
  override render() {
    return html`<input data-slot="input" />`;
  }
}
